### PR TITLE
Mdl 68605 master

### PR DESCRIPTION
**Pull request by septatrix**
Please also update the `*_37` and `*_38` branch accordingly

### CODE REVIEW

**Comment by septatrix** [comment]
@t-schroeder Could you please consider merging this?

**Comment by t-schroeder** [comment]
@septatrix Thanks for fixing my mistake and for writing the test. I hadn't had the time to do it myself.

**Comment by septatrix** [comment]
You're welcome :D I think you missed the `*_37` and `*_38` branch though

**Comment by t-schroeder** [comment]
I squashed both of our commits adding you as the co-author. I hope that's okay. I just want it to be tidy. :)

**Comment by septatrix** [comment]
Yes no problem. I am also a big fan of a clean git history ;)

**Pull request merged**
